<?php

    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator('-');
    $this->headTitle('Zend Framework Tutorial');
    
    echo $this->doctype(); 
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />		
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headScript(); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl(). '/skins/blues/css/text.css'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl(). '/skins/blues/css/layout.css'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl(). '/skins/blues/css/form.css'); ?>
		<?php //echo $this->headLink()->prependStylesheet($this->baseUrl(). '/css/style.css'); ?>
		<?php //echo $this->headLink()->appendStylesheet($this->loadSkin($this->skin)); ?>		
		<?php echo $this->headLink()->prependStylesheet('http://fonts.googleapis.com/css?family=Marvel'); ?>		
	</head>
	<body>
		<div id="pageWrapper">
			<div id="header">
				<p>Zend Framework CMS</p>				
			</div>
			<div id="nav">
				<p><?php echo $this->layout()->nav; ?></p>
			</div>
			<div id="sidebar">
				<div id="subNav">
					<p><?php echo $this->layout()->subNav; ?></p>
				</div>
				
				<div id="adminMenu">
					<p><?php echo $this->layout()->adminMenu; ?></p>
				</div>
				
				<div id="userForm">
					<p><?php echo $this->layout()->userForm; ?></p>
				</div>					
			</div>			
			<div id="main">
				<p><?php echo $this->layout()->content; ?></p>
			</div>
			<div id="footer">
				<p>Copyright &copy; 2012 JOY</p>
			</div>
		</div>
	</body>
</html>